# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98ac3b731cf10b04d904889731c7fb764cbfa4475662d3feef2f3638ecaeb94bc559d8522e53cfd760fe61cf54eaab5f1427b9112d116c40925d44c7c2da982a

test:
  secret_key_base: 880e79aec8a7a66a2f6e8ad41af1065bcc9aaec19be02a5ded723e30b2141681173d6910540c8f26f3d23adce8e8e461e3fd5c4ad8cbab8da03990ae8da83210

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
